export const REGISTRATION_REQUEST: "REGISTRATION_REQUEST" =
  "REGISTRATION_REQUEST";
export const REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS" =
  "REGISTRATION_SUCCESS";
export const REGISTRATION_ERROR: "REGISTRATION_ERROR" = "REGISTRATION_ERROR";

export const AUTHORIZATION_REQUEST: "AUTHORIZATION_REQUEST" =
  "AUTHORIZATION_REQUEST";
export const AUTHORIZATION_SUCCESS: "AUTHORIZATION_SUCCESS" =
  "AUTHORIZATION_SUCCESS";
export const AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR" = "AUTHORIZATION_ERROR";

export const PASSWORD_RECOVERY_REQUEST: "PASSWORD_RECOVERY_REQUEST" =
  "PASSWORD_RECOVERY_REQUEST";
export const PASSWORD_RECOVERY_SUCCESS: "PASSWORD_RECOVERY_SUCCESS" =
  "PASSWORD_RECOVERY_SUCCESS";
export const PASSWORD_RECOVERY_ERROR: "PASSWORD_RECOVERY_ERROR" =
  "PASSWORD_RECOVERY_ERROR";

export const PASSWORD_UPDATING_REQUEST: "PASSWORD_UPDATING_REQUEST" =
  "PASSWORD_UPDATING_REQUEST";
export const PASSWORD_UPDATING_SUCCESS: "PASSWORD_RECOVERY_SUCCESS" =
  "PASSWORD_RECOVERY_SUCCESS";
export const PASSWORD_UPDATING_ERROR: "PASSWORD_UPDATING_ERROR" =
  "PASSWORD_UPDATING_ERROR";

export const LOGOUT_REQUEST: "LOGOUT_REQUEST" = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS: "LOGOUT_SUCCESS" = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR: "LOGOUT_ERROR" = "LOGOUT_ERROR";

export const GET_USER_INFO_REQUEST: "GET_USER_INFO_REQUEST" =
  "GET_USER_INFO_REQUEST";
export const GET_USER_INFO_SUCCESS: "GET_USER_INFO_SUCCESS" =
  "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_ERROR: "GET_USER_INFO_ERROR" = "GET_USER_INFO_ERROR";

export const UPDATE_USER_INFO_REQUEST: "UPDATE_USER_INFO_REQUEST" =
  "UPDATE_USER_INFO_REQUEST";
export const UPDATE_USER_INFO_SUCCESS: "UPDATE_USER_INFO_SUCCESS" =
  "UPDATE_USER_INFO_SUCCESS";
export const UPDATE_USER_INFO_ERROR: "UPDATE_USER_INFO_ERROR" =
  "UPDATE_USER_INFO_ERROR";

export const REFRESH_TOKEN_REQUEST: "REFRESH_TOKEN_REQUEST" =
  "REFRESH_TOKEN_REQUEST";
export const REFRESH_TOKEN_SUCCESS: "REFRESH_TOKEN_SUCCESS" =
  "REFRESH_TOKEN_SUCCESS";
  export const REFRESH_TOKEN_ERROR: "REFRESH_TOKEN_ERROR" =
    "REFRESH_TOKEN_ERROR";
